### ISSUE TITLE
Invalid savepath when updating config file

### ISSUE THREAD

**Issue by OnsenManju** [Enerdy/KeyChanger#5]
Reported here: https://tshock.co/xf/index.php?threads/keychangerssc.2528/page-4#post-47247

In Config.cs, 
https://github.com/Enerdy/KeyChanger/blob/master/Config.cs#L83
``savepath += "KeyChangerConfig.json";``
should be 
``savepath = Path.Combine(savepath, "KeyChangerConfig.json");``

**Comment by Enerdy** [comment]
Oh wow, how did this even happen...

**Comment by OnsenManju** [comment]
How fast :laughing: Thanks a lot!
